import type { Metadata } from 'next'
import '../styles/globals.scss'
import { Footer, Header } from '@/shared/components'

export const metadata: Metadata = {
  title: 'Pixel Forge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
        <main>{children}</main>
      <Footer />
    </>
  )
}
