import type { Metadata } from 'next'
import { DM_Sans, Poppins } from 'next/font/google'
import '../globals.scss'
import { Header } from '@/shared/components'

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm-sans',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
   <main>
    <Header/>
    {children}
   </main>
  )
}
